### ISSUE TITLE
can't import generators

### ISSUE THREAD

**Issue by tommyhlw** [scikit-nano/scikit-nano#10]
First I got this response:

>Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
>[GCC 5.4.0 20160609] on linux
>Type "help", "copyright", "credits" or "license" for more information.
 >>>from sknano.generators import SWNTBundleGenerator

>/usr/local/lib/python3.5/dist-packages/sknano/core/refdata/element_data.yaml
>Traceback (most recent call last):
>  File "<stdin>", line 1, in <module>
>  File "/usr/local/lib/python3.5/dist-packages/sknano/generators/__init__.py", line 59, in <module>
>    from ._base import *
>  File "/usr/local/lib/python3.5/dist-packages/sknano/generators/_base.py", line 19, in <module>
>    from sknano.core.atoms import StructureAtom as Atom, StructureAtoms as Atoms
>  File "/usr/local/lib/python3.5/dist-packages/sknano/core/atoms/__init__.py", line 113, in <module>
>    from ._atoms import *
>  File "/usr/local/lib/python3.5/dist-packages/sknano/core/atoms/_atoms.py", line 21, in <module>
>    from sknano.core.refdata import atomic_masses, atomic_mass_symbol_map, \
>  File "/usr/local/lib/python3.5/dist-packages/sknano/core/refdata/__init__.py", line 45, in <module>
>    from ._element_data import *
>  File "/usr/local/lib/python3.5/dist-packages/sknano/core/refdata/_element_data.py", line 21, in <module>
>    'element_data.yaml'))
>  File "/usr/local/lib/python3.5/dist-packages/sknano/core/_io.py", line 299, in loadobj
>    kwargs["Loader"] = Loader
>NameError: name 'Loader' is not defined

I checked out the "_io.py" and realised I need something like "yaml" to define "Loader". This was not obvious from the output...
Then I googled and installed the following:
`$ sudo pip3 install pyyaml`

Now it forwards to less files but still doesn't work:
>Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
>[GCC 5.4.0 20160609] on linux
>Type "help", "copyright", "credits" or "license" for more information.
>>> from sknano.generators import SWNTBundleGenerator

>Traceback (most recent call last):
> File "<stdin>", line 1, in <module>
 > File "/usr/local/lib/python3.5/dist-packages/sknano/generators/__init__.py", line 59, in <module>
 >   from ._base import *
>  File "/usr/local/lib/python3.5/dist-packages/sknano/generators/_base.py", line 19, in <module>
>   from sknano.core.atoms import StructureAtom as Atom, StructureAtoms as Atoms
>  File "/usr/local/lib/python3.5/dist-packages/sknano/core/__init__.py", line 128, in <module>
 >   from ._io import *
 > File "/usr/local/lib/python3.5/dist-packages/sknano/core/_io.py", line 298
  >  return yaml.load(fp, *args, **kwargs)
 >                                       ^
>IndentationError: unindent does not match any outer indentation level

What to do?

**Comment by wzhe09** [comment]
I have met the same problem.
Just try (sudo or not) 
(1) pip uninstall scikit-nano
(2) pip install pyyaml 
(3) pip install scikit-nano
