### ISSUE TITLE
install error : error code 1 ; RuntimeError: Python version 3.4+ required.

### ISSUE THREAD

**Issue by kimyoungjin06** [scikit-nano/scikit-nano#8]
Envelopment : Ubuntu LTS 16.04
# python

Python 2.7.11+ (default, Apr 17 2016, 14:00:29) 
[GCC 5.3.1 20160413] on linux2
# python3

Python 3.5.1+ (default, Mar 30 2016, 22:46:26) 
[GCC 5.3.1 20160330] on linux

I try pip install scikit-nano and I get following message:
# pip3 install scikit-nano

Collecting scikit-nano
  Using cached scikit-nano-0.3.21.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-Y_9XmP/scikit-nano/setup.py", line 17, in <module>
        raise RuntimeError("Python version 3.4+ required.\n\n"
    RuntimeError: Python version 3.4+ required.

```
Sorry, but there are features of Python 3
that I want to take advantage of and without
worrying about Python 2 compatibility.
Therefore, Python 2 support was removed starting
in v0.3.7. Once/if I learn how to automate the
backporting process from the setup script,
I will restore Python 2 support that way.
Until then, if you must install this for Python 2
you're on your own. It shouldn't be difficult
but you'll have to manually backport the package
source code using a Python 3 to Python 2
compatibility library such as the python `future`
module, which provides a python script called
`pasteurize` that can be run on the source
directory to automate the backporting process.
You'll also need to hack this setup script
to remove any exceptions that are raised when
executed under Python 2.

----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Y_9XmP/scikit-nano/

Why occur this error?

I am new into python and ubuntu.

How can I fit it?

**Comment by the-real-droop** [comment]
@kimyoungjin06, Sorry, I haven't had a chance to look into this yet. It's on my TODO list and I will get back to you ASAP.
